### ISSUE TITLE
Installation problem on mac arm

### ISSUE THREAD

**Issue by thomasbordier** [VROOM-Project/pyvroom#70]
Hello,

Has anyone been able to install pyvroom on arm? 

Using pip and Building from source I get an error like :
« …
ERROR: Failed building wheel for pyvroom
Failed to build pyvroom
ERROR: Could not build wheels for pyvroom, which is required to install pyproject.toml-based projects
... »

I also have an error with "conan install --build=openssl --install-folder conan_build ."
The conan 2.0.2 version is installed correctly. 

I could install pyvroom on a docker "--platform=linux/amd64" but it is not efficient in my use.

thank you

**Comment by nilsnolde** [comment]
No idea about ARM tbh, though a more thorough error description would be helpful IMO. In the docker repository arm images are also built, meaning VROOM has no issue with it. 

Are you cross-compiling or compiling on ARM for ARM?

> The conan 2.0.2 version is installed correctly.

Try 1.x, 2.x needs some adjustments pretty sure.

**Comment by jonathf** [comment]
We don't support ARM oficially, but we can add simple patches if that is all it takes to get you there. I made the pip installer, and @nilsnolde made the Conan installer. Maybe one or the other approach will get you there.

Do you mind also reporting which the machine and OS you are working on?

Could you also try building locally from the repository root with:
```bash
pip install -vvv .
```
pasting the output in a file, and posting it here?

**Comment by thomasbordier** [comment]
Thank you for your feedback,

Nilsnolde:

In error I also have:

`
error: subprocess-exited-with-error
  
  × Building wheel for pyvroom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      WARNING:root:Conan not installed and/or no conan build detected. Assuming dependencies are installed.
      INFO:root:running bdist_wheel
      INFO:root:running build
      INFO:root:running build_py
      INFO:root:creating build
      INFO:root:creating build/lib.macosx-12.6-arm64-cpython-310
      INFO:root:creating build/lib.macosx-12.6-arm64-cpython-310/vroom
      INFO:root:copying src/vroom/break_.py -> build/lib.macosx-12.6-arm64-cpython-310/vroom
`

Concerning docker, on an arm image ("FROM python:3.10") I also have the problem (solved by "FROM --platform=linux/amd64 python:3.10" ). But I tested on docker just to try to understand my problem.


Jonathf:

I am on macbook air m1 12.6.4

here is the end of error return for pip install -vvv .:

` ...
In file included from src/_vroom.cpp:1:
  src/bind/_main.cpp:4:10: fatal error: 'main.cpp' file not found
  #include "main.cpp"
           ^~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for pyvroom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/thomasbordier/.pyenv/versions/dev/bin/python3.10 /Users/thomasbordier/.pyenv/versions/dev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /var/folders/fg/wqlhqr2j76gg_xt5x0mrl85m0000gn/T/tmppti51qj5
  cwd: /Users/thomasbordier/Desktop/learning/openstreetmap/vroom/test_install/pyvroom
  Building wheel for pyvroom (pyproject.toml) ... error
  ERROR: Failed building wheel for pyvroom
Failed to build pyvroom
ERROR: Could not build wheels for pyvroom, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/Users/thomasbordier/.pyenv/versions/dev/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/thomasbordier/.pyenv/versions/dev/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/thomasbordier/.pyenv/versions/dev/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 477, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pyvroom, which is required to install pyproject.toml-based projects
Remote version of pip: 23.0.1
Local version of pip:  23.0.1
Was pip installed by pip? True
Removed build tracker: '/private/var/folders/fg/wqlhqr2j76gg_xt5x0mrl85m0000gn/T/pip-build-tracker-223t6lq7'`

**Comment by nilsnolde** [comment]
There were a lot more questions we didn't get an answer to yet. Also please properly format the markdown.

You sure you checked out the git submodules?

> WARNING:root:Conan not installed and/or no conan build detected. Assuming dependencies are installed.

Quite explicit IMO.

I think this will be quite hard to track down tbh. ARM distro should come from the community. Ideally from someone who has some experience with building tool chains for C++ (and maybe pybind11).
